artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_type: postgres

  postgres:
    host: localhost
    port: 5432
    database: BankCustomer
    user: rajusubba
    password_env: null
    schema: public
    table: bank_customers

  export:
    enabled: true
    output_file: artifacts/data_ingestion/raw_snapshot.csv

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/raw_snapshot.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/raw_snapshot.csv
  
data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  processed_train_path: artifacts/data_preprocessing/train_processed.csv
  processed_test_path: artifacts/data_preprocessing/test_processed.csv
  preprocessor_object_path: artifacts/data_preprocessing/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_preprocessing/train_processed.csv
  test_data_path: artifacts/data_preprocessing/test_processed.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_preprocessing/test_processed.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

wandb:
  enabled: true
  entity: rajusubba-project-personal
  project: customer-churn
  job_type: evaluation
  tags: ["churn", "classification", "mlops"]